### ISSUE TITLE
I try to build with MsBuild

### ISSUE THREAD

**Issue by indrasundanese** [ca1e/REngine-MSG-Tool#1]
"C:\REngine-MSG-Tool-main\REngine-msg-tool.sln" (default target) (1) ->
"C:\REngine-MSG-Tool-main\REngine-msg-tool\REngine-msg-tool.csproj" (default target) (2) ->
  C:\REngine-MSG-Tool-main\REngine-msg-tool\REngine-msg-tool.csproj(1,1): error MSB4041: The default XML namespace of t
he project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="
http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the
old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by ca1e** [comment]
what version of Visual Studio do you use? have you try the latest one? vs 2022(17.3.6) with dotnet 6.0.402 works fine for me

**Comment by indrasundanese** [comment]
Nah. i don't have vs 2022
quick question is this tool work for new DLC msg RE8 Gold editon file format?

**Comment by ca1e** [comment]
i havent test that, its just a reverse engineering about REtool.u can search 'REngine REtool' for more infos

**Comment by indrasundanese** [comment]
Ow. ok thank you for ur answer. appreciate.

**Comment by ca1e** [comment]
sure, good luck
